export const FETCH_LIST = 'FETCH_LIST';
export const LIST_MODAL_OPEN = 'LIST_MODAL_OPEN';
export const LIST_MODAL_CLOSE = 'LIST_MODAL_CLOSE';
export const LIST_NEW_ONE_STATE = 'LIST_NEW_ONE_STATE'
export const LIST_CREATE = 'LIST_CREATE';
export const LIST_CREATE_ERROR = 'LIST_CREATE_ERROR';
export const LIST_ERROR = 'LIST_ERROR';
export const LIST_ADD_SONG = 'LIST_ADD_SONG';
export const LIST_REMOVE_SONG = 'LIST_REMOVE_SONG'

export const LIST_INITIATE_SELECT = 'LIST_INITIATE_SELECT';
export const LIST_DO_SELECT = 'LIST_DO_SELECT';
export const LIST_DO_UNSELECT = 'LIST_DO_UNSELECT';
export const LIST_ALL_SELECT = 'LIST_ALL_SELECT';
export const LIST_ALL_UNSELCT = 'LIST_ALL_UNSELCT';
export const LIST_CANCEL_SELECT = 'LIST_CANCEL_SELECT';
export const LIST_DELETE_SELECT = 'LIST_DELETE_SELECT';


