export const AUDIO_LOAD = 'AUDIO_LOAD';
export const AUDIO_ERROR = 'AUDIO_ERROR';
export const AUDIO_SUCCESS = 'AUDIO_SUCCESS';
export const AUDIO_RELEASE = 'AUDIO_RELEASE';
export const AUDIO_PLAY = 'PLAY_AUDIO';
export const AUDIO_PAUSE = 'AUDIO_PAUSE';
export const AUDIO_STOP = 'AUDIO_STOP';
export const AUDIO_RELOAD = 'AUDIO_RELOAD';
export const ON_SLIDER_EDITING = 'ON_SLIDER_EDITING';
export const SET_SLIDER_CURRENT_TIME = 'SET_SLIDER_CURRENT_TIME';
export const SET_AUDIO_LOADING_TIME_COUNTER = 'SET_AUDIO_LOADING_TIME_COUNTER';

